container:
  image: node:22

check_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install
  schedule:
    - cron: "* * * * *"
  test_script: npm start